### ISSUE TITLE
Excellent Plugin, but dates don't work

### ISSUE THREAD

**Issue by Dexmach5723** [jacoblearned/obsidian-template-by-note-name#52]
The plugin works, but it seems to COPY the template, not invoke it. This means that the {date} variable does not work in the frontmatter.

**Comment by jacoblearned** [comment]
@Dexmach5723 Thanks for the feedback! I've released a new version, 1.1.0, that supports both date and time expression evaluation. 

You'll just have to configure your formats in this plugin's settings as well as Obsidian doesn't provide a way to read the user date and time format settings in `Core Plugins -> Templates` from what I can tell.

Also note that you may have to  recreate your template rules in the settings after you update. A near-future version should prevent you from having to do this in the future.

Please let me know if the new version doesn't address your concerns.

**Comment by jacoblearned** [comment]
v1.1.0 fixes this via #54. Please re-open if needed
